"""Smart label generation from mesh object properties.

Generates descriptive, natural-language labels that match what a user
would type as a text prompt.  The goal is: if someone typed this label
into the mesh generator, the output should look like this mesh.

Priority order (best→worst):
1. Objaverse metadata (name + tags) — richest source
2. Object name from Blender (often descriptive: 'Face', 'Sword_blade')
3. File-level label combined with object context
4. Material names (tell us what the object looks like)
5. Geometry analysis (aspect ratio, complexity)

Label quality rules:
- NEVER include numeric IDs, hex hashes, version strings
- NEVER include project/scene names ('blender 3.3 splash', 'iron man blender swap')
- NEVER include Blender internal prefixes (GEO-, HLP-, DP-, etc.)
- Keep labels 2-8 words, natural, lowercase
- Labels should read like user prompts: 'car wheel', 'wooden table leg'
- Foreign words are translated via a JSON cache generated by scripts/translate_labels.py
"""

import json
import re
from pathlib import Path

import numpy as np


def compute_bbox_aspect(vertices):
    """Compute bounding box extents from vertices.

    Returns (width, depth, height) tuple or None on failure.
    """
    if not vertices or len(vertices) < 3:
        return None
    verts = np.array(vertices)
    if not np.all(np.isfinite(verts)):
        return None
    mins = verts.min(axis=0)
    maxs = verts.max(axis=0)
    extents = maxs - mins
    return tuple(extents.tolist())


# ── Translation cache (generated by scripts/translate_labels.py via Qwen) ──
_TRANSLATIONS_PATH = Path(__file__).resolve().parent.parent / "data" / "label_translations.json"
_TRANSLATION_CACHE: dict[str, str] = {}

def _load_translation_cache():
    """Load Qwen-generated translations from JSON cache."""
    global _TRANSLATION_CACHE
    if _TRANSLATIONS_PATH.exists():
        try:
            _TRANSLATION_CACHE = json.loads(_TRANSLATIONS_PATH.read_text())
        except Exception:
            _TRANSLATION_CACHE = {}

_load_translation_cache()

# Compile a regex for cached translation replacement (whole words only)
def _build_translation_re():
    if not _TRANSLATION_CACHE:
        return None
    return re.compile(
        r'\b(' + '|'.join(
            re.escape(k) for k in sorted(_TRANSLATION_CACHE, key=len, reverse=True)
        ) + r')\b',
        re.IGNORECASE,
    )

_TRANSLATION_RE = _build_translation_re()


def _translate_foreign(text):
    """Replace known foreign words with English equivalents from cache."""
    if not _TRANSLATION_RE or not _TRANSLATION_CACHE:
        return text
    def _repl(m):
        return _TRANSLATION_CACHE.get(m.group(0).lower(), m.group(0))
    return _TRANSLATION_RE.sub(_repl, text)


# ── Cleaning helpers ──────────────────────────────────────────────────

def _strip_numeric_ids(text):
    """Remove BlendSwap-style numeric ID prefixes and 'popular' marker."""
    text = re.sub(r'^\d+\s+popular\b[,\s]*', '', text)
    text = re.sub(r'^\d+[_\s]+', '', text)
    return text.strip()


def _strip_blender_prefixes(text):
    """Remove Blender internal prefixes (GEO-, HLP-, etc.)."""
    prefixes = ['geo ', 'geo-', 'hlp ', 'hlp-', 'dp ', 'dp-',
                'grp ', 'grp-', 'rig ', 'rig-', 'ctrl ', 'ctrl-',
                'def ', 'def-', 'mch ', 'mch-', 'org ', 'org-',
                'wgt ', 'wgt-', 'emt ', 'emt-']
    lower = text.lower()
    for p in prefixes:
        if lower.startswith(p):
            text = text[len(p):]
            lower = text.lower()
    return text.strip()


def _strip_hex_uids(text):
    """Remove hex UIDs (Objaverse-style 32-char hashes)."""
    text = re.sub(r'\b[0-9a-f]{8,}\b', '', text)
    return re.sub(r'\s+', ' ', text).strip()


def _strip_encoding_artifacts(text):
    """Remove encoding artifacts like ⁇ and escaped chars."""
    text = text.replace('\u2047', '')
    text = re.sub(r'\\x[0-9a-f]{2}', '', text)
    return re.sub(r'\s+', ' ', text).strip()


def _strip_version_parts(text):
    """Clean version/part identifiers: 's12', 'v1.2', 'v.4', '.001'."""
    text = re.sub(r'\bv\.?\d+(\.\d+)*\b', '', text)
    text = re.sub(r'\bs\d+\b', '', text)
    text = re.sub(r'\.\d{3,}\b', '', text)  # .001 suffixes
    return re.sub(r'\s+', ' ', text).strip()


def _strip_scene_project_names(text):
    """Remove scene/project name patterns that are NOT object descriptions."""
    # 'blender 3.3 splash' -> ''
    text = re.sub(r'\bblender\s+\d+\.\d+\s+splash\b', '', text, flags=re.I)
    # 'blender swap' or 'blenderswap'
    text = re.sub(r'\bblender\s*swap\b', '', text, flags=re.I)
    # 'splash pokedstudio' style
    text = re.sub(r'\bsplash\s+\w+studio\b', '', text, flags=re.I)
    # 'studio,' prefix for Italian models
    text = re.sub(r'\boggetti\s+studio\b', '', text, flags=re.I)
    # 'cycles,' suffix (render engine name)
    text = re.sub(r'\bcycles\b', '', text, flags=re.I)
    # Scene description patterns like 'lone monk and exposure node demo'
    text = re.sub(r'\b\w+\s+(?:and\s+)?(?:exposure|node|demo|setup|test|sample|example)\s*(?:\w+\s*)*\b(?=\s|$)', '', text, flags=re.I)
    # 'by AuthorName' credits
    text = re.sub(r'\bby\s+\w+\b', '', text, flags=re.I)
    # Project/author prefixes we've seen
    for name in ('lone monk', 'exposure node demo', 'node demo',
                 'archiviz', 'hair nodes', 'ik rig', 'lp',
                 'stylized levi', 'exhibition', 'final',
                 'water 0.99', 'optimized', 'sunna koji2ug',
                 'the white room jay hardy', 'hennessey gt',
                 'augalas', 'dono maison', 'humphh',
                 'warpglow', 'hullgrey', 'hullgraydark',
                 'neroluc', 'plast nera'):
        text = re.sub(r'\b' + re.escape(name) + r'\b', '', text, flags=re.I)
    # Franchise / universe noise that sneaks in from Objaverse metadata
    # e.g. "sd macross sdf 1 macross launch! characters creatures" → discard
    franchise_words = frozenset({
        'macross', 'gundam', 'evangelion', 'pokemon', 'minecraft',
        'fortnite', 'warcraft', 'starcraft', 'hearthstone', 'overwatch',
        'halflife', 'tf2', 'counterstrike', 'valorant', 'skyrim',
        'oblivion', 'fallout', 'diablo', 'warframe', 'dota', 'league',
    })
    words = text.lower().split()
    franchise_hits = sum(1 for w in words if w in franchise_words)
    if franchise_hits >= 2 or (franchise_hits == 1 and len(words) <= 4):
        # Label heavily dominated by franchise names — discard
        return ''
    return re.sub(r'\s+', ' ', text).strip()


def _is_material_only_label(label: str) -> bool:
    """Return True if label consists entirely of material/color words.
    
    Labels like "metal", "wood dry", "grey stone" describe surface properties,
    not what the 3D object IS.  These poison text→geometry alignment because
    the model learns that any mesh can be "metal".
    """
    if not label:
        return True
    words = re.split(r'[\s,]+', label.lower().strip())
    words = [w for w in words if w]
    if not words:
        return True
    meaningful = [w for w in words if w not in _MATERIAL_ONLY_WORDS]
    return len(meaningful) == 0


def _is_low_quality_label(label: str) -> bool:
    """Return True if label should be discarded as low-quality.

    Catches patterns that slip through individual cleaners:
    - Overly long run-on strings that are scene/file descriptions
    - Labels made of mostly exclamation marks / punctuation
    - Labels with >6 comma-separated tokens (tag-dump from metadata)
    - Labels consisting entirely of material/color words
    """
    if not label:
        return True
    # Too many words → likely file/scene description, not a mesh prompt
    words = label.split()
    if len(words) > 10:
        return True
    # Tag dumps: more than 3 comma-separated segments.
    # Real object labels use spaces, not commas.
    # "medieval sword" = good.  "sword, bouncing, candy" = tag soup.
    # Threshold 3 keeps "plank, wood" (1 comma) while catching
    # "sword, bouncing, candy, metal" (3 commas).
    if label.count(',') >= 3:
        return True
    # Pure punctuation / symbol garbage
    alnum = re.sub(r'[^a-z0-9]', '', label.lower())
    if len(alnum) < 3:
        return True
    # Digits dominate (version numbers, IDs)
    # Threshold 0.5 lets through valid model names like "colt m1911"
    # (4 digits / 9 chars = 0.44) while still catching mostly-numeric junk.
    digit_ratio = sum(c.isdigit() for c in alnum) / max(len(alnum), 1)
    if digit_ratio > 0.5:
        return True
    # Material-only labels (e.g. "metal", "wood dry", "grey")
    if _is_material_only_label(label):
        return True
    return False


def _strip_number_suffixes(text):
    """Remove trailing numbers that are just part IDs: 'hair2', 'leaves1'."""
    # 'hair2' -> 'hair', but keep 'ps4' or '3d'
    text = re.sub(r'(\b[a-z]{3,})\d+\b', r'\1', text)
    return text.strip()


def _clean_label_final(label):
    """Master cleaning pipeline — all passes in order."""
    if not label:
        return ''

    label = label.lower()
    label = label.replace('_', ' ').replace('-', ' ')

    # Structural cleaning
    label = _strip_encoding_artifacts(label)
    label = _strip_numeric_ids(label)
    label = _strip_hex_uids(label)
    label = _strip_blender_prefixes(label)
    label = _strip_version_parts(label)
    label = _strip_scene_project_names(label)
    label = _strip_number_suffixes(label)

    # Translate foreign words AFTER structural cleaning
    label = _translate_foreign(label)

    # Strip behavioral/animation words that describe motion, not shape.
    # "bouncing monkey" → "monkey", "animated spinning top" → "spinning top"
    # ("spinning top" is the object name, "spinning" alone would be stripped)
    _BEHAVIORAL_PREFIXES = {
        'animated', 'bouncing', 'dancing', 'falling', 'floating',
        'flying', 'idle', 'looping', 'rigged', 'rolling', 'rotating',
        'running', 'walking', 'wiggling', 'cycling', 'posing',
        'jumpers', 'spawning', 'spawn',
    }
    words = label.split()
    # Only strip if the behavioral word is a prefix AND something remains
    if len(words) > 1 and words[0] in _BEHAVIORAL_PREFIXES:
        label = ' '.join(words[1:])

    # Remove parenthetical detail markers (added back by rebuild_cache)
    label = re.sub(r'\s*\((?:detailed|high-detail)\)\s*', '', label)

    # Remove redundant punctuation and whitespace
    label = re.sub(r'[,\s]{2,}', ', ', label)
    label = re.sub(r'\s+', ' ', label)
    label = label.strip(' ,.:;')

    # Remove words that are just single letters or digits
    words = label.split()
    words = [w for w in words if len(w) > 1 or w in ('a',)]
    label = ' '.join(words)

    if len(label) < 2:
        return ''

    return label


# Object names that are Blender defaults or truly non-descriptive.
# NOTE: Do NOT add legitimate geometry terms here! 'bezier curve',
# 'icosphere', 'torus', 'nurbs' etc. describe real geometry concepts
# that the model should learn.
_USELESS_NAMES = frozenset({
    'object', 'mesh', 'empty', 'camera', 'light',
    'lamp', 'armature', 'bone', 'surface', 'text',
    'default', 'untitled', 'n/a', 'none', '', 'scene',
    'group', 'collection', 'world', 'render', 'view',
    'part', 'piece', 'item', 'thing', 'stuff', 'model',
    'room', 'roomoff', 'room object', 'roomoff object',
    'roomlight', 'roomlight object', 'roomlightoff',
    'roomlightoff object',
    'body',  # too generic as standalone
    # Blender internal object types that leak as names
    'irradiancevolume', 'irradiance volume', 'lightprobe',
    'lattice', 'dummy', 'point', 'base',
    # Non-English single words
    'curva', 'curvas', 'beton', 'noeud',
})

# Material names that provide no useful visual info.
# Only Blender defaults, gibberish, and technical internals — NOT real
# material/color names like "metal", "chrome", "wood".  Those are valid
# descriptors when the material is ACTUALLY applied to the object.
# The quality gate for whether materials are real lives in rebuild_cache.py,
# which only passes material names from properly-applied materials.
_USELESS_MATS = frozenset({
    # Blender defaults
    'material', 'default', 'none', 'mat', 'matte',
    'material.001', 'material.002', 'material.003',
    'material.004', 'material.005',
    'defaultmat', 'pbr dielectric',
    # Generic body/room
    'body', 'body dark', 'body light',
    'roomlight', 'roomlight object', 'roomlightoff',
    'roomlightoff object',
    # Render/technical — Blender internals that leak as material names
    'shadeless', 'wireframe', 'emission', 'transparent',
    'irradiancevolume', 'irradiance volume', 'lightprobe',
    'normale', 'normal', 'luce', 'lux',
    'point', 'vert', 'vertex', 'edge', 'face',
    'toon', 'cel', 'outline',
    # Part numbers / gibberish
    '04', 'dpm', 'flat', 'ral',
    'object', 'objects',
})

# Words that should never be a standalone label (they're material properties,
# not object identities).  Used by _is_material_only_label().
_MATERIAL_ONLY_WORDS = frozenset({
    'metal', 'wood', 'stone', 'glass', 'plastic', 'rubber', 'fabric',
    'concrete', 'brick', 'ceramic', 'leather', 'steel', 'iron',
    'copper', 'brass', 'chrome', 'aluminum', 'aluminium',
    'gold', 'silver', 'bronze',
    'red', 'blue', 'green', 'yellow', 'orange', 'purple', 'pink',
    'white', 'black', 'grey', 'gray', 'brown', 'cyan', 'magenta',
    'dark', 'light', 'bright', 'shiny', 'matte', 'glossy',
    'dry', 'wet', 'rough', 'smooth',
})

# Metadata tags to skip — these describe the *project/listing*, not the
# physical mesh.  Anything here will NOT be appended to labels.
_SKIP_TAGS = frozenset({
    # Platform / format / generic 3D
    '3d', 'model', 'blender', 'object', 'free', 'download',
    'asset', 'game', 'low', 'poly', 'high', 'sketchfab', 'maya',
    'unity', 'unreal', 'fbx', 'glb', 'gltf', 'obj', 'stl',
    'vr', 'ar', 'xr', 'pbr', 'render', 'realtime',
    # Behavioral / animation (describe motion, not shape)
    'animated', 'animation', 'bouncing', 'spinning', 'rotating',
    'walking', 'running', 'idle', 'flying', 'falling', 'rolling',
    'dancing', 'looping', 'loop', 'wiggle', 'floating', 'rigged',
    'rig', 'posed', 'poseable', 'action', 'cycle', 'keyframe',
    # Production / meta (describe workflow, not object)
    'scene', 'test', 'wip', 'draft', 'practice', 'demo',
    'tutorial', 'study', 'sketch', 'concept', 'template',
    'sample', 'example', 'reference', 'preview', 'prototype',
    # Abstract / mood / style (too vague for mesh labels)
    'candy', 'fun', 'cool', 'nice', 'epic', 'awesome', 'cute',
    'scary', 'dark', 'bright', 'stylized', 'realistic', 'cartoon',
    'retro', 'modern', 'classic', 'fantasy', 'scifi', 'sci-fi',
    # Process (describe how it was made, not what it is)
    'baked', 'unwrapped', 'weighted', 'textured', 'sculpted',
    'retopo', 'retopology', 'topology', 'decimated', 'optimized',
    # Overly generic nouns
    'item', 'thing', 'stuff', 'piece', 'part', 'element',
})

# Tags that describe physical objects/properties — only these get appended.
# If a tag matches this set, it's safe to include in the label.
_PHYSICAL_TAGS = frozenset({
    # Materials / surface
    'metal', 'wood', 'wooden', 'glass', 'stone', 'concrete',
    'plastic', 'fabric', 'leather', 'ceramic', 'rubber', 'steel',
    'iron', 'copper', 'gold', 'silver', 'bronze', 'chrome',
    'marble', 'granite', 'brick', 'clay', 'paper', 'cardboard',
    # Object categories
    'furniture', 'vehicle', 'weapon', 'tool', 'building',
    'architecture', 'clothing', 'food', 'plant', 'animal',
    'character', 'creature', 'robot', 'machine', 'mechanical',
    'organic', 'nature', 'industrial', 'medieval', 'military',
    # Shape/size descriptors
    'small', 'large', 'tiny', 'giant', 'round', 'flat',
    'curved', 'angular', 'modular', 'detailed',
})

# Internal-only Blender name prefixes (never meaningful in labels).
# Only strip words that are NEVER useful as geometry descriptions.
_TECHNICAL_WORDS = frozenset({
    'hlp', 'dp', 'grp', 'ctrl', 'mch', 'org', 'wgt',
    'emt', 'lod', 'lod0', 'lod1', 'lod2',
    'mdef', 'transp', 'ao', 'uvdeformed', 'uvmap',
    'coresolidmaterial',
})

# Words that are project/character names, not mesh descriptions
_PROJECT_NAMES = frozenset({
    'sintel', 'pokedstudio', 'neeloo', 'quadbot',
    'bodychan', 'applejack', 'blendrig', 'blenrig',
    'iemniak', '2iemniak', 'albinmerle', 'koji2ug',
    'archiviz', 'humphh', 'augalas', 'minecraftrigs',
    'namifinishing',
})


# Bare primitive names — objects named after the Blender default they
# were created from.  These need CONTEXTUAL enrichment because "Cube.012"
# tells us nothing about what the geometry actually represents.
_PRIMITIVE_NAMES = frozenset({
    'cube', 'sphere', 'cylinder', 'plane', 'circle', 'cone',
    'torus', 'grid', 'icosphere', 'beziercurve', 'beziercircle',
    'nurbspath', 'nurbscircle', 'curve', 'path', 'nurbs',
    'uvsphere',
})


def _is_primitive_name(name):
    """True if name is just a bare Blender primitive (possibly with .001)."""
    clean = re.sub(r'\.\d+$', '', name.lower().strip())
    clean = clean.replace('_', '').replace('-', '').replace(' ', '')
    return clean in _PRIMITIVE_NAMES


def _contextualize_primitive(prim_name, material_names=None,
                             file_label="", sibling_names=None):
    """Build a contextual label for a primitive-named object.

    Instead of labeling "Cube.007" as just "cube", we look at what
    surrounds it:
      - Material tells us WHAT it is: mat='Hair' → 'hair'
      - File label gives scene context: file='elastic_deform_snake_hook' → 'snake hook'
      - Sibling names tell us what else is in the scene

    Returns a descriptive label or '' if no context available.
    """
    # Clean the primitive type (cube, cylinder, bezier curve, etc.)
    prim_clean = re.sub(r'\.\d+$', '', prim_name.lower().strip())
    prim_clean = prim_clean.replace('_', ' ').replace('-', ' ')
    # Normalize compound names: 'beziercurve' → 'bezier curve'
    prim_clean = re.sub(r'(bezier)(curve|circle)', r'\1 \2', prim_clean)
    prim_clean = re.sub(r'(nurbs)(path|circle)', r'\1 \2', prim_clean)
    prim_clean = re.sub(r'(uv)(sphere)', r'\1 \2', prim_clean)

    # Names that are Blender internals / non-descriptive as sibling context
    _BAD_SIBLING_NAMES = frozenset({
        'camera', 'light', 'lamp', 'sun', 'spot', 'area', 'empty',
        'armature', 'gpencil', 'grease pencil', 'bone', 'rig',
    })

    context_parts = []

    # 1. Material names — can hint at WHAT the object is.
    #    rebuild_cache.py only sends material names from objects with REAL
    #    materials, so we trust everything we receive.
    #    - Identity names ("hair", "umbrella stick") → use alone
    #    - Material-type names ("metal", "chrome") → combine with primitive
    #      type for a descriptive label: "metal cube", "chrome sphere"
    if material_names:
        good_mats = []
        for m in material_names:
            cm = _clean_mat_name(m)
            cm = cm.replace('.', ' ').strip()
            cm = re.sub(r'\s+', ' ', cm)
            if cm and len(cm) > 1:
                good_mats.append(cm)
        if good_mats:
            mat = good_mats[0]
            if _is_material_only_label(mat):
                # Material-type word: "metal cube" > "metal"
                context_parts.append(mat + ' ' + prim_clean)
            else:
                # Identity word: "hair" > "hair cube"
                context_parts.append(mat)

    # 2. Sibling names — other objects reveal the scene.
    #    IMPORTANT: sibling names must NOT replace the label entirely.
    #    A "Cube" in a scene with "Suzanne" is NOT a suzanne — it's a
    #    cube that happens to be near a suzanne.  We skip sibling-only
    #    context because it poisons training: the model learns that a
    #    sphere mesh = "suzanne" just because Suzanne was a neighbor.
    #    Sibling context without the primitive type is misleading.
    #    Instead, we fall through to let other strategies handle it,
    #    or the object gets skipped by the quality gate (which is correct).
    # (Disabled — sibling names caused label contamination.)

    # 3. File label — scene-level context
    if file_label and not context_parts:
        cf = _clean_label_final(file_label)
        if cf and len(cf) > 2 and cf not in _USELESS_NAMES:
            context_parts.append(cf)

    if not context_parts:
        return ''  # No context — caller will fall through to other strategies

    # Build label from semantic context only.
    # Important: do NOT append primitive substrate (cube/cylinder/plane/etc)
    # because that pollutes text->shape semantics for part labels.
    # e.g. prefer "hair" over "hair cube".
    context = context_parts[0]
    return _clean_label_final(context)


def _clean_obj_name(name):
    """Clean a Blender object name into a label-safe string."""
    if not name:
        return ''
    name = re.sub(r'\.\d{3,}$', '', name).strip()
    name = name.lower().replace('_', ' ').replace('-', ' ')
    name = _strip_blender_prefixes(name)
    name = _strip_hex_uids(name)
    name = _strip_version_parts(name)
    name = _strip_number_suffixes(name)
    words = name.split()
    words = [w for w in words if w not in _TECHNICAL_WORDS and w not in _PROJECT_NAMES]
    name = ' '.join(words)
    name = _translate_foreign(name)
    if name in _USELESS_NAMES or re.match(r'^[\d\s]+$', name):
        return ''
    return name.strip()


def _clean_mat_name(mat):
    """Clean a material name for use in labels."""
    if not mat or not isinstance(mat, str):
        return ''
    m = re.sub(r'\.\d{3,}$', '', mat).strip().lower()
    m = m.replace('_', ' ').replace('-', ' ').replace('.', ' ')
    m = _strip_hex_uids(m)
    m = _strip_number_suffixes(m)
    words = m.split()
    words = [w for w in words if w not in _TECHNICAL_WORDS and w not in _PROJECT_NAMES]
    m = ' '.join(words)
    m = _translate_foreign(m)
    if m in _USELESS_MATS or re.match(r'^material\s*\d*$', m):
        return ''
    return m.strip()


def _build_geo_desc(bbox_aspect, num_faces):
    """Build geometry descriptors from bounding box and face count."""
    parts = []
    if bbox_aspect is not None:
        w, d, h = bbox_aspect
        max_dim = max(w, d, h)
        min_dim = min(w, d, h) + 0.001
        ratio = max_dim / min_dim
        if ratio > 4:
            if h > w and h > d:
                parts.append('tall')
            elif w > h * 2 and d > h * 2:
                parts.append('flat')
            else:
                parts.append('elongated')
        elif ratio < 1.5:
            if num_faces < 50:
                parts.append('simple')
    if not parts:
        if num_faces < 20:
            parts.append('simple')
        elif num_faces > 1000:
            parts.append('detailed')
    return parts


def generate_smart_label(obj_name="", material_names=None, modifier_types=None,
                         num_faces=0, num_verts=0, bbox_aspect=None,
                         file_label="", metadata_name="",
                         metadata_desc="", metadata_tags=None,
                         metadata_categories=None, sibling_names=None):
    """Generate a descriptive single-object label from all available info.

    Returns a natural-language label (max 100 chars) suitable as a
    text-to-mesh prompt.

    ``sibling_names`` is a list of OTHER object names in the same file,
    used to contextualise bare-primitive names like 'Cube.007'.
    """

    clean_obj = _clean_obj_name(obj_name)
    clean_mats = [m for m in (_clean_mat_name(n) for n in (material_names or [])) if m]
    geo_desc = _build_geo_desc(bbox_aspect, num_faces)

    # Clean file label
    clean_file = ''
    if file_label:
        clean_file = _clean_label_final(file_label)
        if clean_file in _USELESS_NAMES or re.match(r'^[\d\s]+$', clean_file):
            clean_file = ''

    # ── Strategy 0: Primitive with context ──
    # Objects named 'Cube.007', 'Plane.012', 'BezierCurve' etc. need
    # enrichment from materials / siblings / file to be useful labels.
    if _is_primitive_name(obj_name):
        ctx_label = _contextualize_primitive(
            obj_name,
            material_names=material_names,
            file_label=file_label,
            sibling_names=sibling_names,
        )
        if ctx_label and len(ctx_label) > 2:
            return ctx_label[:100]
        # No context found — fall through to remaining strategies

    # ── Strategy 1: Rich Objaverse metadata ──
    if metadata_name and metadata_name.lower().strip() not in _USELESS_NAMES:
        label = _clean_label_final(metadata_name)
        if label and len(label) > 2 and not _is_low_quality_label(label):
            # Only append tags that describe PHYSICAL properties of the
            # object (material, category, shape).  Skip behavioral,
            # animation, platform, and abstract/mood tags — these describe
            # the project, not the mesh.
            if metadata_tags and len(label.split()) < 4:
                useful_tags = []
                for t in (metadata_tags or [])[:5]:
                    tag = t if isinstance(t, str) else t.get('name', '')
                    tag = tag.strip().lower()
                    if (tag and tag not in _SKIP_TAGS
                            and tag in _PHYSICAL_TAGS
                            and tag not in label):
                        useful_tags.append(tag)
                if useful_tags:
                    # Use space, not comma — build a description, not a tag list
                    label = label + ' ' + ' '.join(useful_tags[:2])
            candidate = label.strip()[:100]
            if not _is_low_quality_label(candidate):
                return candidate

    # ── Strategy 2: Object name + file context ──
    if clean_obj and len(clean_obj) > 2:
        # Combine with file label for context if they differ
        if clean_file and clean_file != clean_obj and clean_file not in clean_obj:
            # File gives scene context, obj gives specific part
            # e.g. file='country kitchen', obj='table cross' -> 'kitchen table cross piece'
            label = _clean_label_final(clean_file + ' ' + clean_obj)
        else:
            label = clean_obj
        # Append ONE material if it adds descriptive info (color/material type).
        # Material suffixes are fine — they're real data if the mesh keeps its materials.
        if clean_mats and clean_mats[0] not in label:
            mat = clean_mats[0]
            if len(mat) > 2 and not mat.startswith(label.split()[0]):
                label = label + ', ' + mat
        if label and len(label) > 2 and not _is_low_quality_label(label):
            return _clean_label_final(label)[:100]

    # ── Strategy 3: File label alone (single-object files) ──
    if clean_file and len(clean_file) > 2 and not _is_low_quality_label(clean_file):
        label = clean_file
        if clean_mats and clean_mats[0] not in label:
            label = label + ', ' + clean_mats[0]
        candidate = _clean_label_final(label)[:100]
        if not _is_low_quality_label(candidate):
            return candidate

    # ── Strategy 4: Material-based description ──
    # rebuild_cache.py only sends real material names, so trust them.
    # _is_low_quality_label() still catches pure-material standalone labels.
    if clean_mats:
        good_mats = [m for m in clean_mats if len(m) > 2][:2]
        if good_mats:
            desc = ' '.join(geo_desc) + ' ' if geo_desc else ''
            candidate = _clean_label_final(desc + ', '.join(good_mats))[:100]
            if candidate and not _is_low_quality_label(candidate):
                return candidate

    # ── Strategy 5: Pure geometry (last resort) ──
    # Return empty string so the caller knows we couldn't generate a real label.
    # The caller (rebuild_cache) will skip items with empty/weak labels.
    return ''
